<?php
/**
 * Photobooth Configuration
 * Generated by install.sh — edit this file to change settings.
 *
 * After editing, restart Apache: sudo systemctl restart apache2
 */

date_default_timezone_set('Europe/London');

// ── Organisation ──────────────────────────────────────────────────────────────
define('ORG_NAME',          '{{ORG_NAME}}');

// ── Paths ─────────────────────────────────────────────────────────────────────
define('PHOTO_BASE_DIR',    '/var/photobooth/photos');
define('LOG_DIR',           '/var/log/photobooth');
define('LOGO_PATH',         '/etc/photobooth/logo.png');
define('SCHEDULE_FILE',     '/etc/photobooth/schedule.json');

// ── Photo settings ────────────────────────────────────────────────────────────
define('FILENAME_FORMAT',   'd-m-Y');       // Date portion of photo filename
define('JPEG_QUALITY',      95);            // JPEG save quality (1–100)
define('LOGO_SIZE',         150);           // Logo width in pixels (composited on canvas)
define('LOGO_MARGIN',       20);            // Logo margin from edge in pixels
define('QR_EXPIRY_DAYS',    30);            // Days before download token expires
define('RETENTION_DAYS',    365);           // Days to keep photos before cleanup

// ── Download URL ──────────────────────────────────────────────────────────────
// Used in QR codes and email links. Must be reachable by phones.
// Local mode example:  http://192.168.1.100
// Public mode example: https://photobooth.example.com
// Public mode (custom port): https://photobooth.example.com:8444
define('DOWNLOAD_BASE_URL', '{{DOWNLOAD_BASE_URL}}');

// ── Email / SMTP ──────────────────────────────────────────────────────────────
// Set SMTP_ENABLED to false to disable the email feature entirely.
define('SMTP_ENABLED',      {{SMTP_ENABLED}});
define('SMTP_HOST',         '{{SMTP_HOST}}');
define('SMTP_PORT',         {{SMTP_PORT}});
define('SMTP_SECURE',       '{{SMTP_SECURE}}');   // 'tls' or 'ssl'
define('SMTP_USER',         '{{SMTP_USER}}');
define('SMTP_PASS',         '{{SMTP_PASS}}');
define('SMTP_FROM',         '{{SMTP_FROM}}');
define('SMTP_FROM_NAME',    '{{SMTP_FROM_NAME}}');
